<a href="https://colab.research.google.com/github/haticenurcakr/turkish-classic-books-finetuning/blob/main/05_turk_klasik_kitaplari_ozel_benchmark.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import json
import random
import pandas as pd

SEED = 42
random.seed(SEED)

# 50 kitap ve yazarları
KITAPLAR = {
    "Taaşşuk-ı Talat ve Fitnat": "Şemsettin Sami",
    "İntibah": "Namık Kemal",
    "Cezmi": "Namık Kemal",
    "Felatun Bey ile Rakım Efendi": "Ahmet Mithat Efendi",
    "Araba Sevdası": "Recaizade Mahmud Ekrem",
    "Sergüzeşt": "Samipaşazade Sezai",
    "Zehra": "Nabizade Nazım",
    "Gulyabani": "Hüseyin Rahmi Gürpınar",
    "Esrar-ı Cinayat": "Ahmet Mithat Efendi",
    "Turfanda mı Yoksa Turfa mı": "Mizancı Murad",
    "Karabibik": "Nabizade Nazım",
    "Mai ve Siyah": "Halit Ziya Uşaklıgil",
    "Aşk-ı Memnu": "Halit Ziya Uşaklıgil",
    "Kırık Hayatlar": "Halit Ziya Uşaklıgil",
    "Huzur": "Ahmet Hamdi Tanpınar",
    "Bir Ölünün Defteri": "Halit Ziya Uşaklıgil",
    "Ferdi ve Şürekası": "Halit Ziya Uşaklıgil",
    "Eylül": "Mehmet Rauf",
    "Şıpsevdi": "Hüseyin Rahmi Gürpınar",
    "Mürebbiye": "Hüseyin Rahmi Gürpınar",
    "Kuyruklu Yıldız Altında Bir İzdivaç": "Hüseyin Rahmi Gürpınar",
    "Sözde Kızlar": "Peyami Safa",
    "Çalıkuşu": "Reşat Nuri Güntekin",
    "Yaprak Dökümü": "Reşat Nuri Güntekin",
    "Acımak": "Reşat Nuri Güntekin",
    "Dudaktan Kalbe": "Reşat Nuri Güntekin",
    "Damga": "Reşat Nuri Güntekin",
    "Yeşil Gece": "Reşat Nuri Güntekin",
    "Yalnızız": "Peyami Safa",
    "Ateşten Gömlek": "Halide Edib Adıvar",
    "Vurun Kahpeye": "Halide Edib Adıvar",
    "Sinekli Bakkal": "Halide Edib Adıvar",
    "Tatarcık": "Halide Edib Adıvar",
    "Handan": "Halide Edib Adıvar",
    "Yeni Turan": "Halide Edib Adıvar",
    "Yaban": "Yakup Kadri Karaosmanoğlu",
    "Kiralık Konak": "Yakup Kadri Karaosmanoğlu",
    "Ankara": "Yakup Kadri Karaosmanoğlu",
    "Sodom ve Gomore": "Yakup Kadri Karaosmanoğlu",
    "Hüküm Gecesi": "Yakup Kadri Karaosmanoğlu",
    "Matmazel Noraliya'nın Koltuğu": "Peyami Safa",
    "Dokuzuncu Hariciye Koğuşu": "Peyami Safa",
    "Fatih-Harbiye": "Peyami Safa",
    "Bir Tereddüdün Romanı": "Peyami Safa",
    "Mahşer": "Peyami Safa",
    "Kuyucaklı Yusuf": "Sabahattin Ali",
    "İçimizdeki Şeytan": "Sabahattin Ali",
    "Kürk Mantolu Madonna": "Sabahattin Ali",
    "Ayaşlı ile Kiracıları": "Memduh Şevket Esendal",
    "Saatleri Ayarlama Enstitüsü": "Ahmet Hamdi Tanpınar"
}

# En az 10 isteniyordu; burada 25 soru elle hazırlanmıştır.
ELLE_HAZIRLANAN = [
    (
        "edebiyat_tarihi",
        "Batılı anlamda yazılmış ilk Türkçe romanlardan biri kabul edilen eser hangisidir?",
        "Taaşşuk-ı Talat ve Fitnat",
        ["Mai ve Siyah", "Yaban", "Huzur"]
    ),
    (
        "edebiyat_tarihi",
        "Türk edebiyatının ilk tarihî romanı olarak bilinen eser hangisidir?",
        "Cezmi",
        ["İntibah", "Karabibik", "Sergüzeşt"]
    ),
    (
        "edebiyat_tarihi",
        "Türk edebiyatının ilk realist romanı olarak kabul edilen eser hangisidir?",
        "Araba Sevdası",
        ["Eylül", "Zehra", "Şıpsevdi"]
    ),
    (
        "edebiyat_tarihi",
        "Köy yaşamını gerçekçi biçimde ele alan ilk Türk romanı kabul edilen eser hangisidir?",
        "Karabibik",
        ["Yaban", "Yeşil Gece", "Kuyucaklı Yusuf"]
    ),
    (
        "edebiyat_tarihi",
        "Türk edebiyatının ilk psikolojik romanı olarak kabul edilen eser hangisidir?",
        "Eylül",
        ["Dokuzuncu Hariciye Koğuşu", "Mai ve Siyah", "Yalnızız"]
    ),
    (
        "karakter",
        "Bihruz Bey hangi romanın başkahramanıdır?",
        "Araba Sevdası",
        ["Felatun Bey ile Rakım Efendi", "Şıpsevdi", "Mai ve Siyah"]
    ),
    (
        "karakter",
        "Raif Efendi ve Maria Puder hangi romanda yer alır?",
        "Kürk Mantolu Madonna",
        ["İçimizdeki Şeytan", "Kuyucaklı Yusuf", "Handan"]
    ),
    (
        "karakter",
        "Feride karakteri hangi romanda yer alır?",
        "Çalıkuşu",
        ["Acımak", "Dudaktan Kalbe", "Damga"]
    ),
    (
        "karakter",
        "Ahmet Celal hangi romanın anlatıcı ve başkahramanıdır?",
        "Yaban",
        ["Ankara", "Kiralık Konak", "Sodom ve Gomore"]
    ),
    (
        "karakter",
        "Hayri İrdal hangi romanda yer alır?",
        "Saatleri Ayarlama Enstitüsü",
        ["Huzur", "Yalnızız", "Ayaşlı ile Kiracıları"]
    ),
    (
        "karakter",
        "Ali Rıza Bey ve ailesinin yaşadığı çözülmeyi anlatan roman hangisidir?",
        "Yaprak Dökümü",
        ["Kırık Hayatlar", "Kiralık Konak", "Acımak"]
    ),
    (
        "karakter",
        "Rabia karakteri hangi romanda yer alır?",
        "Sinekli Bakkal",
        ["Tatarcık", "Handan", "Yeni Turan"]
    ),
    (
        "karakter",
        "Neriman ve Şinasi hangi romanda yer alır?",
        "Fatih-Harbiye",
        ["Sözde Kızlar", "Yalnızız", "Mahşer"]
    ),
    (
        "karakter",
        "Yusuf ve Muazzez hangi romanda yer alır?",
        "Kuyucaklı Yusuf",
        ["İçimizdeki Şeytan", "Kürk Mantolu Madonna", "Yaban"]
    ),
    (
        "karakter",
        "Mümtaz ve Nuran hangi romanda yer alır?",
        "Huzur",
        ["Saatleri Ayarlama Enstitüsü", "Mai ve Siyah", "Bir Tereddüdün Romanı"]
    ),
    (
        "karakter",
        "Meftun Bey hangi romanda yanlış Batılılaşmayı temsil eder?",
        "Şıpsevdi",
        ["Mürebbiye", "Gulyabani", "Kuyruklu Yıldız Altında Bir İzdivaç"]
    ),
    (
        "karakter",
        "Mahpeyker, Dilaşub ve Ali Bey hangi romanda yer alır?",
        "İntibah",
        ["Cezmi", "Sergüzeşt", "Zehra"]
    ),
    (
        "karakter",
        "Talat Bey ve Fitnat Hanım hangi eserin başlıca karakterleridir?",
        "Taaşşuk-ı Talat ve Fitnat",
        ["Sergüzeşt", "İntibah", "Araba Sevdası"]
    ),
    (
        "karakter",
        "Bihter ve Adnan Bey hangi romanda yer alır?",
        "Aşk-ı Memnu",
        ["Kırık Hayatlar", "Mai ve Siyah", "Eylül"]
    ),
    (
        "icerik",
        "Doğu-Batı çatışmasını İstanbul'un iki semti üzerinden anlatan roman hangisidir?",
        "Fatih-Harbiye",
        ["Sodom ve Gomore", "Kiralık Konak", "Yeni Turan"]
    ),
    (
        "icerik",
        "Millî Mücadele döneminde aydın ile köylü arasındaki uzaklığı ele alan roman hangisidir?",
        "Yaban",
        ["Ankara", "Ateşten Gömlek", "Vurun Kahpeye"]
    ),
    (
        "icerik",
        "Modernleşme, zaman ve kurumlaşma sorunlarını ironik biçimde işleyen roman hangisidir?",
        "Saatleri Ayarlama Enstitüsü",
        ["Huzur", "Yalnızız", "Ayaşlı ile Kiracıları"]
    ),
    (
        "icerik",
        "Bir hastane koğuşundaki hasta gencin iç dünyasına odaklanan roman hangisidir?",
        "Dokuzuncu Hariciye Koğuşu",
        ["Bir Tereddüdün Romanı", "Mahşer", "Yalnızız"]
    ),
    (
        "icerik",
        "Kurtuluş Savaşı sırasında geçen ve millî mücadeleyi konu alan Halide Edib romanı hangisidir?",
        "Ateşten Gömlek",
        ["Handan", "Tatarcık", "Sinekli Bakkal"]
    ),
    (
        "icerik",
        "II. Selim döneminde Osmanlı-İran savaşları çevresinde gelişen roman hangisidir?",
        "Cezmi",
        ["İntibah", "Hüküm Gecesi", "Yeni Turan"]
    )
]

benchmark = []
harfler = ["A", "B", "C", "D"]
kitap_listesi = list(KITAPLAR.keys())
yazar_listesi = list(set(KITAPLAR.values()))

def kayit_ekle(kategori, soru, dogru, yanlislar, insan_yazimi):
    secenekler = [dogru] + list(yanlislar)
    random.shuffle(secenekler)

    cevap_index = secenekler.index(dogru)

    benchmark.append({
        "kategori": kategori,
        "soru": soru,
        "secenekler": secenekler,
        "cevap": cevap_index,
        "dogru_harf": harfler[cevap_index],
        "dogru_cevap": dogru,
        "insan_yazimi": insan_yazimi,
        "egitimle_birebir_eslesme": False
    })

# Her kitap için iki soru: toplam 100 soru
for kitap, yazar in KITAPLAR.items():

    diger_yazarlar = [
        secenek for secenek in yazar_listesi
        if secenek != yazar
    ]

    kayit_ekle(
        kategori="yazar_bilgisi",
        soru=f"“{kitap}” adlı eserin yazarı aşağıdakilerden hangisidir?",
        dogru=yazar,
        yanlislar=random.sample(diger_yazarlar, 3),
        insan_yazimi=False
    )

    diger_kitaplar = [
        secenek for secenek in kitap_listesi
        if secenek != kitap and KITAPLAR[secenek] != yazar
    ]

    kayit_ekle(
        kategori="eser_bilgisi",
        soru=f"Aşağıdaki eserlerden hangisi {yazar} tarafından yazılmıştır?",
        dogru=kitap,
        yanlislar=random.sample(diger_kitaplar, 3),
        insan_yazimi=False
    )

# 25 elle hazırlanmış soru
for kategori, soru, dogru, yanlislar in ELLE_HAZIRLANAN:
    kayit_ekle(
        kategori=kategori,
        soru=soru,
        dogru=dogru,
        yanlislar=yanlislar,
        insan_yazimi=True
    )

# Kimlikleri ekle
for i, kayit in enumerate(benchmark, start=1):
    kayit["id"] = f"TKB-{i:03d}"

benchmark_df = pd.DataFrame(benchmark)

# Dosyaları oluştur
benchmark_df.to_json(
    "turk_klasik_kitaplari_benchmark.jsonl",
    orient="records",
    lines=True,
    force_ascii=False
)

benchmark_df.to_csv(
    "turk_klasik_kitaplari_benchmark_kontrol.csv",
    index=False,
    encoding="utf-8-sig"
)

# Kontroller
assert len(benchmark_df) >= 100
assert benchmark_df["id"].nunique() == len(benchmark_df)
assert benchmark_df["cevap"].between(0, 3).all()
assert benchmark_df["insan_yazimi"].sum() >= 10

print("✅ Benchmark oluşturuldu.")
print("Toplam soru:", len(benchmark_df))
print("Elle hazırlanan soru:", int(benchmark_df["insan_yazimi"].sum()))
print("Model ile oluşturulan/düzenlenen soru:", int((~benchmark_df["insan_yazimi"]).sum()))

display(benchmark_df.head(10))

✅ Benchmark oluşturuldu.
Toplam soru: 125
Elle hazırlanan soru: 25
Model ile oluşturulan/düzenlenen soru: 100

,kategori,soru,secenekler,cevap,dogru_harf,dogru_cevap,insan_yazimi,egitimle_birebir_eslesme,id
0,yazar_bilgisi,“Taaşşuk-ı Talat ve Fitnat” adlı eserin yazarı...,"[Hüseyin Rahmi Gürpınar, Memduh Şevket Esendal...",2,C,Şemsettin Sami,False,False,TKB-001
1,eser_bilgisi,Aşağıdaki eserlerden hangisi Şemsettin Sami ta...,"[Gulyabani, Turfanda mı Yoksa Turfa mı, Ayaşlı...",3,D,Taaşşuk-ı Talat ve Fitnat,False,False,TKB-002
2,yazar_bilgisi,“İntibah” adlı eserin yazarı aşağıdakilerden h...,"[Mehmet Rauf, Peyami Safa, Namık Kemal, Yakup ...",2,C,Namık Kemal,False,False,TKB-003
3,eser_bilgisi,Aşağıdaki eserlerden hangisi Namık Kemal taraf...,"[Huzur, Ankara, İntibah, Kürk Mantolu Madonna]",2,C,İntibah,False,False,TKB-004
4,yazar_bilgisi,“Cezmi” adlı eserin yazarı aşağıdakilerden han...,"[Sabahattin Ali, Halit Ziya Uşaklıgil, Ahmet M...",3,D,Namık Kemal,False,False,TKB-005
5,eser_bilgisi,Aşağıdaki eserlerden hangisi Namık Kemal taraf...,"[Mürebbiye, Cezmi, Mai ve Siyah, Yaprak Dökümü]",1,B,Cezmi,False,False,TKB-006
6,yazar_bilgisi,“Felatun Bey ile Rakım Efendi” adlı eserin yaz...,"[Ahmet Mithat Efendi, Peyami Safa, Yakup Kadri...",0,A,Ahmet Mithat Efendi,False,False,TKB-007
7,eser_bilgisi,Aşağıdaki eserlerden hangisi Ahmet Mithat Efen...,"[Ayaşlı ile Kiracıları, Sinekli Bakkal, Cezmi,...",3,D,Felatun Bey ile Rakım Efendi,False,False,TKB-008
8,yazar_bilgisi,“Araba Sevdası” adlı eserin yazarı aşağıdakile...,"[Samipaşazade Sezai, Recaizade Mahmud Ekrem, H...",1,B,Recaizade Mahmud Ekrem,False,False,TKB-009
9,eser_bilgisi,Aşağıdaki eserlerden hangisi Recaizade Mahmud ...,"[Sergüzeşt, Araba Sevdası, Cezmi, İçimizdeki Ş...",1,B,Araba Sevdası,False,False,TKB-010

In [ ]:
!pip install -q -U datasets huggingface_hub pyarrow

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 555.1/555.1 kB 11.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 774.9/774.9 kB 30.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 50.1/50.1 MB 18.4 MB/s eta 0:00:00

In [ ]:
!pip install -q -U huggingface_hub

In [ ]:
from huggingface_hub import HfApi, notebook_login
from pathlib import Path

notebook_login()

HF_USERNAME = "haticenurcakr"
BENCHMARK_REPO = f"{HF_USERNAME}/turk-klasik-kitaplari-benchmark"

api = HfApi()

# Dataset reposunu oluştur
api.create_repo(
    repo_id=BENCHMARK_REPO,
    repo_type="dataset",
    exist_ok=True,
    private=False
)

# JSONL dosyasını yükle
api.upload_file(
    path_or_fileobj="turk_klasik_kitaplari_benchmark.jsonl",
    path_in_repo="data/test.jsonl",
    repo_id=BENCHMARK_REPO,
    repo_type="dataset",
    commit_message="Upload 125-question benchmark"
)

# Kontrol CSV dosyasını yükle
api.upload_file(
    path_or_fileobj="turk_klasik_kitaplari_benchmark_kontrol.csv",
    path_in_repo="data/benchmark_kontrol.csv",
    repo_id=BENCHMARK_REPO,
    repo_type="dataset",
    commit_message="Upload benchmark control table"
)

print("✅ Benchmark yüklendi.")
print(f"https://huggingface.co/datasets/{BENCHMARK_REPO}")

✅ Benchmark yüklendi.
https://huggingface.co/datasets/haticenurcakr/turk-klasik-kitaplari-benchmark

In [ ]:
dataset_card = """---
language:
- tr
license: mit
task_categories:
- question-answering
tags:
- turkish
- literature
- benchmark
- multiple-choice
pretty_name: Türk Klasik Kitapları Özel Benchmark
---

# Türk Klasik Kitapları Özel Benchmark

Bu veri seti, Türk klasik romanları alanında dil modellerini değerlendirmek amacıyla hazırlanmış 125 soruluk çoktan seçmeli bir benchmark çalışmasıdır.

## Veri Setinin Yapısı

- Toplam soru: 125
- Elle hazırlanmış soru: 25
- Yazar-eser sorusu: 100
- Seçenek sayısı: 4
- Dil: Türkçe
- Kullanım amacı: Fine-tune modelini farklı modellerle karşılaştırmak

## Kategoriler

- Yazar bilgisi
- Eser bilgisi
- Karakter bilgisi
- Roman içeriği
- Türk edebiyatı tarihi

## Sütunlar

- `id`: Sorunun benzersiz kimliği
- `kategori`: Sorunun kategorisi
- `soru`: Çoktan seçmeli soru
- `secenekler`: Dört cevap seçeneği
- `cevap`: Doğru seçeneğin sıfır tabanlı indeksi
- `dogru_harf`: Doğru seçeneğin harfi
- `dogru_cevap`: Doğru cevabın metni
- `insan_yazimi`: Sorunun elle hazırlanıp hazırlanmadığı

## Metodoloji Notu

Fine-tune modeli daha önce hazırlandığı için bu çalışma eğitimden önce ayrılmış klasik bir holdout split değildir. Eğitim sorularıyla birebir aynı olmayacak şekilde hazırlanmış yeni bir özel alan değerlendirme setidir.

Model daha sonra yeniden eğitilirse bu benchmark eğitim verisinin dışında tutulmalıdır.

## Bağlantılar

- Eğitim veri seti: https://huggingface.co/datasets/haticenurcakr/turkish-classic-books-qa
- Fine-tune LoRA modeli: https://huggingface.co/haticenurcakr/turkish-classic-books-qwen-lora
"""

Path("README_BENCHMARK.md").write_text(
    dataset_card,
    encoding="utf-8"
)

api.upload_file(
    path_or_fileobj="README_BENCHMARK.md",
    path_in_repo="README.md",
    repo_id=BENCHMARK_REPO,
    repo_type="dataset",
    commit_message="Add benchmark dataset card"
)

print("✅ Dataset Card eklendi.")
print(f"https://huggingface.co/datasets/{BENCHMARK_REPO}")

✅ Dataset Card eklendi.
https://huggingface.co/datasets/haticenurcakr/turk-klasik-kitaplari-benchmark

In [ ]:
!pip install -q -U transformers peft accelerate bitsandbytes sentencepiece

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.6/11.6 MB 60.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 40.9/40.9 MB 17.3 MB/s eta 0:00:00

In [ ]:
import gc
import re
import time
import torch
import pandas as pd

from peft import PeftConfig, PeftModel
from transformers import (
    AutoModelForCausalLM,
    AutoTokenizer,
    BitsAndBytesConfig
)

assert torch.cuda.is_available(), "Önce Colab'dan T4 GPU seçmelisin."

print("GPU:", torch.cuda.get_device_name(0))

LORA_MODEL = "haticenurcakr/turkish-classic-books-qwen-lora"

# LoRA'nın eğitildiği base modeli otomatik öğren
peft_config = PeftConfig.from_pretrained(LORA_MODEL)
BASE_MODEL = peft_config.base_model_name_or_path

MODELLER = [
    {
        "etiket": "Qwen Base",
        "model": BASE_MODEL,
        "lora": None
    },
    {
        "etiket": "Qwen + Türk Klasik Kitapları LoRA",
        "model": BASE_MODEL,
        "lora": LORA_MODEL
    },
    {
        "etiket": "SmolLM2 1.7B Instruct",
        "model": "HuggingFaceTB/SmolLM2-1.7B-Instruct",
        "lora": None
    },
    {
        "etiket": "TinyLlama 1.1B Chat",
        "model": "TinyLlama/TinyLlama-1.1B-Chat-v1.0",
        "lora": None
    },
    {
        "etiket": "StableLM Zephyr 1.6B",
        "model": "stabilityai/stablelm-2-zephyr-1_6b",
        "lora": None
    }
]

print("Base model:", BASE_MODEL)

for ayar in MODELLER:
    print("-", ayar["etiket"], "=>", ayar["model"])

GPU: Tesla T4

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

adapter_config.json:   0%|          | 0.00/1.25k [00:00<?, ?B/s]

Base model: unsloth/Qwen2.5-1.5B-Instruct-bnb-4bit
- Qwen Base => unsloth/Qwen2.5-1.5B-Instruct-bnb-4bit
- Qwen + Türk Klasik Kitapları LoRA => unsloth/Qwen2.5-1.5B-Instruct-bnb-4bit
- SmolLM2 1.7B Instruct => HuggingFaceTB/SmolLM2-1.7B-Instruct
- TinyLlama 1.1B Chat => TinyLlama/TinyLlama-1.1B-Chat-v1.0
- StableLM Zephyr 1.6B => stabilityai/stablelm-2-zephyr-1_6b

In [ ]:
quantization_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_compute_dtype=torch.float16,
    bnb_4bit_use_double_quant=True
)

HARFLER = ["A", "B", "C", "D"]


def modeli_yukle(model_id, lora_id=None):

    tokenizer = AutoTokenizer.from_pretrained(
        model_id,
        trust_remote_code=True
    )

    tokenizer.padding_side = "left"

    if tokenizer.pad_token_id is None:
        tokenizer.pad_token = tokenizer.eos_token

    model = AutoModelForCausalLM.from_pretrained(
        model_id,
        quantization_config=quantization_config,
        device_map="auto",
        trust_remote_code=True
    )

    if lora_id is not None:
        model = PeftModel.from_pretrained(
            model,
            lora_id
        )

    model.eval()

    return model, tokenizer


def prompt_hazirla(tokenizer, soru, secenekler):

    secenek_metni = "\n".join(
        f"{HARFLER[i]}) {secenek}"
        for i, secenek in enumerate(secenekler)
    )

    istek = (
        "Aşağıdaki Türk edebiyatı sorusunu cevapla. "
        "Yalnızca doğru seçeneğin harfini yaz. "
        "Açıklama yapma.\n\n"
        f"Soru: {soru}\n"
        f"{secenek_metni}\n"
        "Cevap:"
    )

    messages = [
        {
            "role": "user",
            "content": istek
        }
    ]

    try:
        return tokenizer.apply_chat_template(
            messages,
            tokenize=False,
            add_generation_prompt=True
        )
    except Exception:
        return istek


def cevap_harfini_bul(metin):

    metin = str(metin).upper().strip()

    eslesme = re.search(
        r"(?:^|\s|[(:])([ABCD])(?:\s|$|[).,:])",
        metin
    )

    if eslesme:
        return eslesme.group(1)

    if len(metin) > 0 and metin[0] in HARFLER:
        return metin[0]

    return None


def benchmark_calistir(ayar, veri, batch_size=8):

    print("\n" + "=" * 60)
    print("Test edilen model:", ayar["etiket"])
    print("=" * 60)

    model, tokenizer = modeli_yukle(
        ayar["model"],
        ayar["lora"]
    )

    baslangic = time.time()
    kayitlar = []

    for baslangic_index in range(
        0,
        len(veri),
        batch_size
    ):

        parca = veri.iloc[
            baslangic_index:
            baslangic_index + batch_size
        ]

        promptlar = [
            prompt_hazirla(
                tokenizer,
                satir.soru,
                list(satir.secenekler)
            )
            for satir in parca.itertuples()
        ]

        inputs = tokenizer(
            promptlar,
            return_tensors="pt",
            padding=True,
            truncation=True,
            max_length=1024
        ).to(model.device)

        with torch.inference_mode():

            outputs = model.generate(
                **inputs,
                max_new_tokens=4,
                do_sample=False,
                pad_token_id=tokenizer.pad_token_id
            )

        yeni_tokenler = outputs[
            :,
            inputs["input_ids"].shape[1]:
        ]

        cevap_metinleri = tokenizer.batch_decode(
            yeni_tokenler,
            skip_special_tokens=True
        )

        for (_, satir), ham_cevap in zip(
            parca.iterrows(),
            cevap_metinleri
        ):

            tahmin = cevap_harfini_bul(
                ham_cevap
            )

            dogru_mu = (
                tahmin == satir["dogru_harf"]
            )

            kayitlar.append({
                "model": ayar["etiket"],
                "model_id": (
                    ayar["lora"]
                    if ayar["lora"] is not None
                    else ayar["model"]
                ),
                "soru_id": satir["id"],
                "kategori": satir["kategori"],
                "dogru_harf": satir["dogru_harf"],
                "model_tahmini": tahmin,
                "ham_cevap": ham_cevap.strip(),
                "dogru_mu": bool(dogru_mu)
            })

        tamamlanan = min(
            baslangic_index + batch_size,
            len(veri)
        )

        dogru_sayisi = sum(
            kayit["dogru_mu"]
            for kayit in kayitlar
        )

        print(
            f"\r{tamamlanan}/{len(veri)} | "
            f"Doğru: {dogru_sayisi} | "
            f"Başarı: "
            f"%{100 * dogru_sayisi / tamamlanan:.2f}",
            end=""
        )

    toplam_sure = time.time() - baslangic

    detay_df = pd.DataFrame(kayitlar)

    ozet = {
        "model": ayar["etiket"],
        "model_id": (
            ayar["lora"]
            if ayar["lora"] is not None
            else ayar["model"]
        ),
        "toplam_soru": len(detay_df),
        "dogru_cevap": int(
            detay_df["dogru_mu"].sum()
        ),
        "yanlis_cevap": int(
            (~detay_df["dogru_mu"]).sum()
        ),
        "gecersiz_cevap": int(
            detay_df["model_tahmini"].isna().sum()
        ),
        "basari_yuzdesi": round(
            100 * detay_df["dogru_mu"].mean(),
            2
        ),
        "sure_saniye": round(
            toplam_sure,
            2
        )
    }

    print(
        f"\nTamamlandı: "
        f"%{ozet['basari_yuzdesi']}"
    )

    del model
    del tokenizer

    gc.collect()
    torch.cuda.empty_cache()

    return ozet, detay_df

In [ ]:
import pandas as pd

BENCHMARK_URL = (
    "https://huggingface.co/datasets/"
    "haticenurcakr/turk-klasik-kitaplari-benchmark/"
    "resolve/main/data/test.jsonl"
)

benchmark_df = pd.read_json(
    BENCHMARK_URL,
    lines=True
)

print("✅ Benchmark yeniden yüklendi.")
print("Toplam soru:", len(benchmark_df))

display(benchmark_df.head())

✅ Benchmark yeniden yüklendi.
Toplam soru: 125

,kategori,soru,secenekler,cevap,dogru_harf,dogru_cevap,insan_yazimi,egitimle_birebir_eslesme,id
0,yazar_bilgisi,“Taaşşuk-ı Talat ve Fitnat” adlı eserin yazarı...,"[Hüseyin Rahmi Gürpınar, Memduh Şevket Esendal...",2,C,Şemsettin Sami,False,False,TKB-001
1,eser_bilgisi,Aşağıdaki eserlerden hangisi Şemsettin Sami ta...,"[Gulyabani, Turfanda mı Yoksa Turfa mı, Ayaşlı...",3,D,Taaşşuk-ı Talat ve Fitnat,False,False,TKB-002
2,yazar_bilgisi,“İntibah” adlı eserin yazarı aşağıdakilerden h...,"[Mehmet Rauf, Peyami Safa, Namık Kemal, Yakup ...",2,C,Namık Kemal,False,False,TKB-003
3,eser_bilgisi,Aşağıdaki eserlerden hangisi Namık Kemal taraf...,"[Huzur, Ankara, İntibah, Kürk Mantolu Madonna]",2,C,İntibah,False,False,TKB-004
4,yazar_bilgisi,“Cezmi” adlı eserin yazarı aşağıdakilerden han...,"[Sabahattin Ali, Halit Ziya Uşaklıgil, Ahmet M...",3,D,Namık Kemal,False,False,TKB-005

In [ ]:
tum_ozetler = []
tum_detaylar = []

for ayar in MODELLER:

    ozet, detay = benchmark_calistir(
        ayar=ayar,
        veri=benchmark_df,
        batch_size=8
    )

    tum_ozetler.append(ozet)
    tum_detaylar.append(detay)

print("\n✅ Beş modelin testi tamamlandı.")

============================================================
Test edilen model: Qwen Base
============================================================

config.json:   0%|          | 0.00/1.34k [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/7.36k [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/2.78M [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/1.67M [00:00<?, ?B/s]

tokenizer.json: reconstructing file:   0%|          |  0.00B / 11.4MB

tokenizer.json: downloading bytes:           |  0.00B

added_tokens.json:   0%|          | 0.00/605 [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/614 [00:00<?, ?B/s]

/usr/local/lib/python3.12/dist-packages/transformers/quantizers/auto.py:271: UserWarning: You passed `quantization_config` or equivalent parameters to `from_pretrained` but the model you're loading already has a `quantization_config` attribute. The `quantization_config` from the model will be used.
  warnings.warn(warning_msg)

model.safetensors: reconstructing file:   0%|          |  0.00B / 1.14GB

model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/338 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/270 [00:00<?, ?B/s]

[transformers] Both `max_new_tokens` (=4) and `max_length`(=32768) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=4) and `max_length`(=32768) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

8/125 | Doğru: 2 | Başarı: %25.00

[transformers] Both `max_new_tokens` (=4) and `max_length`(=32768) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

16/125 | Doğru: 2 | Başarı: %12.50

[transformers] Both `max_new_tokens` (=4) and `max_length`(=32768) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

24/125 | Doğru: 5 | Başarı: %20.83

[transformers] Both `max_new_tokens` (=4) and `max_length`(=32768) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

32/125 | Doğru: 5 | Başarı: %15.62

[transformers] Both `max_new_tokens` (=4) and `max_length`(=32768) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

40/125 | Doğru: 6 | Başarı: %15.00

[transformers] Both `max_new_tokens` (=4) and `max_length`(=32768) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

48/125 | Doğru: 8 | Başarı: %16.67

[transformers] Both `max_new_tokens` (=4) and `max_length`(=32768) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

56/125 | Doğru: 12 | Başarı: %21.43

[transformers] Both `max_new_tokens` (=4) and `max_length`(=32768) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

64/125 | Doğru: 14 | Başarı: %21.88

[transformers] Both `max_new_tokens` (=4) and `max_length`(=32768) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

72/125 | Doğru: 17 | Başarı: %23.61

[transformers] Both `max_new_tokens` (=4) and `max_length`(=32768) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

80/125 | Doğru: 18 | Başarı: %22.50

[transformers] Both `max_new_tokens` (=4) and `max_length`(=32768) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

88/125 | Doğru: 20 | Başarı: %22.73

[transformers] Both `max_new_tokens` (=4) and `max_length`(=32768) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

96/125 | Doğru: 22 | Başarı: %22.92

[transformers] Both `max_new_tokens` (=4) and `max_length`(=32768) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

104/125 | Doğru: 23 | Başarı: %22.12

[transformers] Both `max_new_tokens` (=4) and `max_length`(=32768) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

112/125 | Doğru: 24 | Başarı: %21.43

[transformers] Both `max_new_tokens` (=4) and `max_length`(=32768) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

125/125 | Doğru: 26 | Başarı: %20.80
Tamamlandı: %20.8

============================================================
Test edilen model: Qwen + Türk Klasik Kitapları LoRA
============================================================

Loading weights:   0%|          | 0/338 [00:00<?, ?it/s]

adapter_model.safetensors: reconstructing file:   0%|          |  0.00B / 73.9MB

adapter_model.safetensors: downloading bytes:           |  0.00B

[transformers] Both `max_new_tokens` (=4) and `max_length`(=32768) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=4) and `max_length`(=32768) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

8/125 | Doğru: 1 | Başarı: %12.50

[transformers] Both `max_new_tokens` (=4) and `max_length`(=32768) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

16/125 | Doğru: 1 | Başarı: %6.25

[transformers] Both `max_new_tokens` (=4) and `max_length`(=32768) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

24/125 | Doğru: 2 | Başarı: %8.33

[transformers] Both `max_new_tokens` (=4) and `max_length`(=32768) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

32/125 | Doğru: 2 | Başarı: %6.25

[transformers] Both `max_new_tokens` (=4) and `max_length`(=32768) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

40/125 | Doğru: 3 | Başarı: %7.50

[transformers] Both `max_new_tokens` (=4) and `max_length`(=32768) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

48/125 | Doğru: 5 | Başarı: %10.42

[transformers] Both `max_new_tokens` (=4) and `max_length`(=32768) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

56/125 | Doğru: 7 | Başarı: %12.50

[transformers] Both `max_new_tokens` (=4) and `max_length`(=32768) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

64/125 | Doğru: 9 | Başarı: %14.06

[transformers] Both `max_new_tokens` (=4) and `max_length`(=32768) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

72/125 | Doğru: 11 | Başarı: %15.28

[transformers] Both `max_new_tokens` (=4) and `max_length`(=32768) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

80/125 | Doğru: 12 | Başarı: %15.00

[transformers] Both `max_new_tokens` (=4) and `max_length`(=32768) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

88/125 | Doğru: 14 | Başarı: %15.91

[transformers] Both `max_new_tokens` (=4) and `max_length`(=32768) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

96/125 | Doğru: 15 | Başarı: %15.62

[transformers] Both `max_new_tokens` (=4) and `max_length`(=32768) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

104/125 | Doğru: 16 | Başarı: %15.38

[transformers] Both `max_new_tokens` (=4) and `max_length`(=32768) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

112/125 | Doğru: 17 | Başarı: %15.18

[transformers] Both `max_new_tokens` (=4) and `max_length`(=32768) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

125/125 | Doğru: 19 | Başarı: %15.20
Tamamlandı: %15.2

============================================================
Test edilen model: SmolLM2 1.7B Instruct
============================================================

config.json:   0%|          | 0.00/908 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/3.76k [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/801k [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/466k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/655 [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/2.10M [00:00<?, ?B/s]

model.safetensors: reconstructing file:   0%|          |  0.00B / 3.42GB

model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/218 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/132 [00:00<?, ?B/s]

125/125 | Doğru: 10 | Başarı: %8.00
Tamamlandı: %8.0

============================================================
Test edilen model: TinyLlama 1.1B Chat
============================================================

config.json:   0%|          | 0.00/608 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/1.29k [00:00<?, ?B/s]

tokenizer.model: reconstructing file:   0%|          |  0.00B /  500kB

tokenizer.model: downloading bytes:           |  0.00B

tokenizer.json:   0%|          | 0.00/1.84M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/551 [00:00<?, ?B/s]

model.safetensors: reconstructing file:   0%|          |  0.00B / 2.20GB

model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/201 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/124 [00:00<?, ?B/s]

[transformers] Both `max_new_tokens` (=4) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=4) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

8/125 | Doğru: 0 | Başarı: %0.00

[transformers] Both `max_new_tokens` (=4) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

16/125 | Doğru: 2 | Başarı: %12.50

[transformers] Both `max_new_tokens` (=4) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

24/125 | Doğru: 2 | Başarı: %8.33

[transformers] Both `max_new_tokens` (=4) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

32/125 | Doğru: 3 | Başarı: %9.38

[transformers] Both `max_new_tokens` (=4) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

40/125 | Doğru: 3 | Başarı: %7.50

[transformers] Both `max_new_tokens` (=4) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

48/125 | Doğru: 3 | Başarı: %6.25

[transformers] Both `max_new_tokens` (=4) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

56/125 | Doğru: 3 | Başarı: %5.36

[transformers] Both `max_new_tokens` (=4) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

64/125 | Doğru: 4 | Başarı: %6.25

[transformers] Both `max_new_tokens` (=4) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

72/125 | Doğru: 4 | Başarı: %5.56

[transformers] Both `max_new_tokens` (=4) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

80/125 | Doğru: 6 | Başarı: %7.50

[transformers] Both `max_new_tokens` (=4) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

88/125 | Doğru: 7 | Başarı: %7.95

[transformers] Both `max_new_tokens` (=4) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

96/125 | Doğru: 8 | Başarı: %8.33

[transformers] Both `max_new_tokens` (=4) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

104/125 | Doğru: 8 | Başarı: %7.69

[transformers] Both `max_new_tokens` (=4) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

112/125 | Doğru: 8 | Başarı: %7.14

[transformers] Both `max_new_tokens` (=4) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

125/125 | Doğru: 8 | Başarı: %6.40
Tamamlandı: %6.4

============================================================
Test edilen model: StableLM Zephyr 1.6B
============================================================

config.json:   0%|          | 0.00/608 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/1.40k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/4.24M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/784 [00:00<?, ?B/s]

model.safetensors: reconstructing file:   0%|          |  0.00B / 3.29GB

model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/340 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/121 [00:00<?, ?B/s]

[transformers] Ignoring clean_up_tokenization_spaces=True for BPE tokenizer TokenizersBackend. The clean_up_tokenization post-processing step is designed for WordPiece tokenizers and is destructive for BPE (it strips spaces before punctuation). Set clean_up_tokenization_spaces=False to suppress this warning, or set clean_up_tokenization_spaces_for_bpe_even_though_it_will_corrupt_output=True to force cleanup anyway.

125/125 | Doğru: 12 | Başarı: %9.60
Tamamlandı: %9.6

✅ Beş modelin testi tamamlandı.

In [ ]:
import pandas as pd
from huggingface_hub import HfApi

BENCHMARK_REPO = "haticenurcakr/turk-klasik-kitaplari-benchmark"

# Genel sonuçlar
ozet_df = pd.DataFrame(tum_ozetler)

ozet_df = ozet_df.sort_values(
    by="basari_yuzdesi",
    ascending=False
).reset_index(drop=True)

# Bütün modellerin soru bazlı cevapları
detay_df = pd.concat(
    tum_detaylar,
    ignore_index=True
)

# Kategori bazlı sonuçlar
kategori_df = (
    detay_df
    .groupby(["model", "kategori"])["dogru_mu"]
    .agg(["sum", "count", "mean"])
    .reset_index()
)

kategori_df = kategori_df.rename(
    columns={
        "sum": "dogru_cevap",
        "count": "toplam_soru"
    }
)

kategori_df["basari_yuzdesi"] = (
    kategori_df["mean"] * 100
).round(2)

kategori_df = kategori_df.drop(
    columns=["mean"]
)

# Dosyaları kaydet
ozet_df.to_csv(
    "ozel_benchmark_5_model_ozet.csv",
    index=False,
    encoding="utf-8-sig"
)

detay_df.to_csv(
    "ozel_benchmark_5_model_detay.csv",
    index=False,
    encoding="utf-8-sig"
)

kategori_df.to_csv(
    "ozel_benchmark_kategori_sonuclari.csv",
    index=False,
    encoding="utf-8-sig"
)

print("GENEL SONUÇLAR")
display(ozet_df)

print("\nKATEGORİ SONUÇLARI")
display(kategori_df)

GENEL SONUÇLAR

,model,model_id,toplam_soru,dogru_cevap,yanlis_cevap,gecersiz_cevap,basari_yuzdesi,sure_saniye
0,StableLM Zephyr 1.6B,stabilityai/stablelm-2-zephyr-1_6b,125,29,96,0,23.2,3.36
1,Qwen + Türk Klasik Kitapları LoRA,haticenurcakr/turkish-classic-books-qwen-lora,125,28,97,0,22.4,26.45
2,Qwen Base,unsloth/Qwen2.5-1.5B-Instruct-bnb-4bit,125,27,98,0,21.6,26.98
3,TinyLlama 1.1B Chat,TinyLlama/TinyLlama-1.1B-Chat-v1.0,125,26,99,0,20.8,6.00
4,SmolLM2 1.7B Instruct,HuggingFaceTB/SmolLM2-1.7B-Instruct,125,25,100,0,20.0,8.73

KATEGORİ SONUÇLARI

,model,kategori,dogru_cevap,toplam_soru,basari_yuzdesi
0,Qwen + Türk Klasik Kitapları LoRA,edebiyat_tarihi,1,5,20.00
1,Qwen + Türk Klasik Kitapları LoRA,eser_bilgisi,13,50,26.00
2,Qwen + Türk Klasik Kitapları LoRA,icerik,1,6,16.67
3,Qwen + Türk Klasik Kitapları LoRA,karakter,2,14,14.29
4,Qwen + Türk Klasik Kitapları LoRA,yazar_bilgisi,11,50,22.00
5,Qwen Base,edebiyat_tarihi,1,5,20.00
6,Qwen Base,eser_bilgisi,12,50,24.00
7,Qwen Base,icerik,1,6,16.67
8,Qwen Base,karakter,2,14,14.29
9,Qwen Base,yazar_bilgisi,11,50,22.00
10,SmolLM2 1.7B Instruct,edebiyat_tarihi,1,5,20.00
11,SmolLM2 1.7B Instruct,eser_bilgisi,9,50,18.00
12,SmolLM2 1.7B Instruct,icerik,1,6,16.67
13,SmolLM2 1.7B Instruct,karakter,2,14,14.29
14,SmolLM2 1.7B Instruct,yazar_bilgisi,12,50,24.00
15,StableLM Zephyr 1.6B,edebiyat_tarihi,3,5,60.00
16,StableLM Zephyr 1.6B,eser_bilgisi,15,50,30.00
17,StableLM Zephyr 1.6B,icerik,1,6,16.67
18,StableLM Zephyr 1.6B,karakter,3,14,21.43
19,StableLM Zephyr 1.6B,yazar_bilgisi,7,50,14.00
20,TinyLlama 1.1B Chat,edebiyat_tarihi,1,5,20.00
21,TinyLlama 1.1B Chat,eser_bilgisi,8,50,16.00
22,TinyLlama 1.1B Chat,icerik,1,6,16.67
23,TinyLlama 1.1B Chat,karakter,2,14,14.29
24,TinyLlama 1.1B Chat,yazar_bilgisi,14,50,28.00

In [ ]:
gecersiz_ornekler = (
    detay_df[
        detay_df["model_tahmini"].isna()
    ]
    .groupby("model")
    .head(5)
)

display(
    gecersiz_ornekler[
        [
            "model",
            "soru_id",
            "dogru_harf",
            "ham_cevap"
        ]
    ]
)

                                 model  soru_id dogru_harf      ham_cevap
3                            Qwen Base  TKB-004          C    Namık Kemal
5                            Qwen Base  TKB-006          B    Namık Kemal
9                            Qwen Base  TKB-010          B  Harfi giriniz
126  Qwen + Türk Klasik Kitapları LoRA  TKB-002          D         çırak-
127  Qwen + Türk Klasik Kitapları LoRA  TKB-003          C    Namık Kemal
128  Qwen + Türk Klasik Kitapları LoRA  TKB-004          C        Intibah
133  Qwen + Türk Klasik Kitapları LoRA  TKB-009          B    Halide Edib
139  Qwen + Türk Klasik Kitapları LoRA  TKB-015          A        Mizancı
250              SmolLM2 1.7B Instruct  TKB-001          C          "Taaş
252              SmolLM2 1.7B Instruct  TKB-003          C           "İnt
256              SmolLM2 1.7B Instruct  TKB-007          A         "Felat
260              SmolLM2 1.7B Instruct  TKB-011          A         "Sergü
262              SmolLM2 1.7B Instruct  TKB-013          D         "Zehra
375                TinyLlama 1.1B Chat  TKB-001          C        Soru: "
377                TinyLlama 1.1B Chat  TKB-003          C        Soru: "
379                TinyLlama 1.1B Chat  TKB-005          D        Soru: "
381                TinyLlama 1.1B Chat  TKB-007          A        Soru: "
383                TinyLlama 1.1B Chat  TKB-009          B        Soru: "
504               StableLM Zephyr 1.6B  TKB-005          D        Soru: “
508               StableLM Zephyr 1.6B  TKB-009          B        Soru: “
509               StableLM Zephyr 1.6B  TKB-010          B      Recaizade
510               StableLM Zephyr 1.6B  TKB-011          A        Soru: “
512               StableLM Zephyr 1.6B  TKB-013          D        Soru: “

In [ ]:
def harf_tokenlerini_bul(tokenizer):

    tokenler = {}

    for harf in HARFLER:
        aday_idler = []

        # Farklı tokenizerların boşluk kullanımını destekle
        for metin in [harf, " " + harf]:

            ids = tokenizer.encode(
                metin,
                add_special_tokens=False
            )

            # Tek token olan seçenekleri kabul et
            if len(ids) == 1:
                aday_idler.append(ids[0])

        aday_idler = list(set(aday_idler))

        if len(aday_idler) == 0:
            raise ValueError(
                f"{harf} için tek token bulunamadı."
            )

        tokenler[harf] = aday_idler

    return tokenler


def benchmark_olasilikla_calistir(
    ayar,
    veri,
    batch_size=8
):

    print("\n" + "=" * 60)
    print("Test edilen model:", ayar["etiket"])
    print("=" * 60)

    model, tokenizer = modeli_yukle(
        ayar["model"],
        ayar["lora"]
    )

    harf_tokenleri = harf_tokenlerini_bul(
        tokenizer
    )

    print("Harf tokenleri:", harf_tokenleri)

    baslama_zamani = time.time()
    kayitlar = []

    for baslangic_index in range(
        0,
        len(veri),
        batch_size
    ):

        parca = veri.iloc[
            baslangic_index:
            baslangic_index + batch_size
        ]

        promptlar = [
            prompt_hazirla(
                tokenizer,
                satir.soru,
                list(satir.secenekler)
            )
            for satir in parca.itertuples()
        ]

        inputs = tokenizer(
            promptlar,
            return_tensors="pt",
            padding=True,
            truncation=True,
            max_length=1024
        ).to(model.device)

        with torch.inference_mode():

            outputs = model(
                **inputs
            )

            # Modelin sıradaki token için ürettiği puanlar
            son_token_logitleri = (
                outputs.logits[:, -1, :].float()
            )

        for satir_sirasi, (_, satir) in enumerate(
            parca.iterrows()
        ):

            harf_puanlari = {}

            for harf in HARFLER:

                token_idleri = harf_tokenleri[harf]

                puanlar = [
                    son_token_logitleri[
                        satir_sirasi,
                        token_id
                    ].item()
                    for token_id in token_idleri
                ]

                harf_puanlari[harf] = max(puanlar)

            # En yüksek olasılığa sahip harf
            tahmin = max(
                harf_puanlari,
                key=harf_puanlari.get
            )

            dogru_mu = (
                tahmin == satir["dogru_harf"]
            )

            kayitlar.append({
                "model": ayar["etiket"],
                "model_id": (
                    ayar["lora"]
                    if ayar["lora"] is not None
                    else ayar["model"]
                ),
                "soru_id": satir["id"],
                "kategori": satir["kategori"],
                "dogru_harf": satir["dogru_harf"],
                "model_tahmini": tahmin,
                "A_puani": harf_puanlari["A"],
                "B_puani": harf_puanlari["B"],
                "C_puani": harf_puanlari["C"],
                "D_puani": harf_puanlari["D"],
                "dogru_mu": bool(dogru_mu)
            })

        tamamlanan = min(
            baslangic_index + batch_size,
            len(veri)
        )

        dogru_sayisi = sum(
            kayit["dogru_mu"]
            for kayit in kayitlar
        )

        print(
            f"\r{tamamlanan}/{len(veri)} | "
            f"Doğru: {dogru_sayisi} | "
            f"Başarı: "
            f"%{100 * dogru_sayisi / tamamlanan:.2f}",
            end=""
        )

    toplam_sure = (
        time.time() - baslama_zamani
    )

    detay = pd.DataFrame(kayitlar)

    ozet = {
        "model": ayar["etiket"],
        "model_id": (
            ayar["lora"]
            if ayar["lora"] is not None
            else ayar["model"]
        ),
        "toplam_soru": len(detay),
        "dogru_cevap": int(
            detay["dogru_mu"].sum()
        ),
        "yanlis_cevap": int(
            (~detay["dogru_mu"]).sum()
        ),
        "gecersiz_cevap": 0,
        "basari_yuzdesi": round(
            100 * detay["dogru_mu"].mean(),
            2
        ),
        "sure_saniye": round(
            toplam_sure,
            2
        )
    }

    print(
        f"\nTamamlandı: "
        f"%{ozet['basari_yuzdesi']}"
    )

    del model
    del tokenizer
    del outputs

    gc.collect()
    torch.cuda.empty_cache()

    return ozet, detay

In [ ]:
# Eski, hatalı sonuçların üzerine yazıyoruz
tum_ozetler = []
tum_detaylar = []

for ayar in MODELLER:

    ozet, detay = benchmark_olasilikla_calistir(
        ayar=ayar,
        veri=benchmark_df,
        batch_size=8
    )

    tum_ozetler.append(ozet)
    tum_detaylar.append(detay)

print("\n✅ Düzeltilmiş beş model testi tamamlandı.")

============================================================
Test edilen model: Qwen Base
============================================================

/usr/local/lib/python3.12/dist-packages/transformers/quantizers/auto.py:271: UserWarning: You passed `quantization_config` or equivalent parameters to `from_pretrained` but the model you're loading already has a `quantization_config` attribute. The `quantization_config` from the model will be used.
  warnings.warn(warning_msg)

Loading weights:   0%|          | 0/338 [00:00<?, ?it/s]

Harf tokenleri: {'A': [32, 362], 'B': [33, 425], 'C': [34, 356], 'D': [35, 422]}
125/125 | Doğru: 27 | Başarı: %21.60
Tamamlandı: %21.6

============================================================
Test edilen model: Qwen + Türk Klasik Kitapları LoRA
============================================================

Loading weights:   0%|          | 0/338 [00:00<?, ?it/s]

Harf tokenleri: {'A': [32, 362], 'B': [33, 425], 'C': [34, 356], 'D': [35, 422]}
125/125 | Doğru: 28 | Başarı: %22.40
Tamamlandı: %22.4

============================================================
Test edilen model: SmolLM2 1.7B Instruct
============================================================

Loading weights:   0%|          | 0/218 [00:00<?, ?it/s]

Harf tokenleri: {'A': [49, 330], 'B': [50, 389], 'C': [51, 340], 'D': [52, 422]}
125/125 | Doğru: 25 | Başarı: %20.00
Tamamlandı: %20.0

============================================================
Test edilen model: TinyLlama 1.1B Chat
============================================================

Loading weights:   0%|          | 0/201 [00:00<?, ?it/s]

Harf tokenleri: {'A': [319], 'B': [350], 'C': [315], 'D': [360]}
125/125 | Doğru: 26 | Başarı: %20.80
Tamamlandı: %20.8

============================================================
Test edilen model: StableLM Zephyr 1.6B
============================================================

Loading weights:   0%|          | 0/340 [00:00<?, ?it/s]

Harf tokenleri: {'A': [32, 362], 'B': [33, 426], 'C': [34, 356], 'D': [35, 423]}
125/125 | Doğru: 29 | Başarı: %23.20
Tamamlandı: %23.2

✅ Düzeltilmiş beş model testi tamamlandı.